services:
  mikopbx:
    image: mikopbx/mikopbx:latest
    container_name: miko-pbx
    restart: always
    ports:
      - "8080:80"
      - "444:443"
      - "5060:5060"
      - "5061:5061"
    volumes:
      - /var/spool/mikopbx/cf:/var/spool/mikopbx/cf
      - /var/spool/mikopbx/storage:/var/spool/mikopbx/storage
    environment:
      - TZ=UTC
    user: "www-user"
    networks:
      - mikopbx_network
      
networks:
  mikopbx_network:
    driver: bridge
